### ISSUE TITLE
After running ./raster, no raster.sln file appears in build.

### ISSUE THREAD

**Issue by grandrx10** [dilevin/computer-graphics-csc317#61]
I have already ran build and ./raster but no raster.sln file is appearing, is there anything I should be aware about?

**Comment by Zhecheng-Wang** [comment]
Please post questions regarding A1 to Github Issue of A1 in the future.
What's your OS? If you are on Linux/Mac, this is expected, there shouldn't be any sln.
If you can build ./raster, you don't have to worry about the sln file. Sln file is just project file for Visual Studio users. We recommend VS for students on Windows because it generally makes building CMake (or C++ graphics project) easier.

**Comment by grandrx10** [comment]
Oh sorry about posting this in the wrong section. I am using Ubuntu, which explains why I didn't get a sln file.

I am still a little confused on how to get the resulting images from ./raster. Where can I get the information on how to use ./raster? Perhaps I missed something major?

**Comment by Zhecheng-Wang** [comment]
Right, so you need to implement write to ppm first, then it will output ppm images when you run ./raster.

**Comment by grandrx10** [comment]
Ah, I think I understand. I must have written write to ppm incorrectly, and thus the file does not appear when I run ./raster. I will go give it a look over.
